import type { ICodeHudAgentCommand } from "./ICodeHudAgentCommand";
import type { ICodeHudAgentEvent } from "./ICodeHudAgentEvent";

/**
 * A live conversation with one coding agent process.
 *
 * Owned by the bridge and never by the device: the harness runs where the
 * repository is, and a session outlives any particular pair of glasses being
 * connected to it.
 *
 * @evidence requirements/agent-control/harness-abstraction.md#agent-session-lifetime Exposes the four operations a live harness conversation offers and nothing else.
 * @evidence specifications/agent-harness/normalized-stream.md#spec-agent-session-open Types the session surface the specification limits to identity, observations, instruction delivery, and idempotent termination.
 * @author Samchon
 */
export interface ICodeHudAgentSession {
  /**
   * Identifier the wire protocol addresses this session by.
   *
   * Generated by the bridge rather than the harness so that harnesses without
   * a session concept still multiplex correctly.
   */
  readonly id: string;

  /**
   * Normalized observations, in the order the adapter produced them.
   *
   * Iterating consumes; the bridge is the sole consumer and fans out to
   * devices, so a device disconnecting never stalls the harness.
   */
  readonly events: AsyncIterable<ICodeHudAgentEvent>;

  /**
   * Submits one instruction to the agent.
   *
   * Resolves once the instruction has been handed to the harness, not once the
   * agent has acted on it; the effect arrives as events.
   */
  send(command: ICodeHudAgentCommand): Promise<void>;

  /**
   * Ends the session and releases the harness process.
   *
   * Closing an already closed session succeeds, because a device and a
   * shutdown handler may both reach for it.
   */
  close(): Promise<void>;
}
