packages:
  - config
  - packages/*
  - test

catalogs:
  typescript:
    ttsc: &ttsc ^0.30.2
    "@ttsc/evidence": *ttsc
    "@ttsc/lint": *ttsc
    typescript: ^7.0.2
    "@trivago/prettier-plugin-sort-imports": ^5.2.2
    prettier: ^3.5.3
    "@wrtnlabs/evidence": ^0.1.0
  samchon:
    typia: ^13.2.0
    "@nestia/e2e": ^12.1.0
  net:
    ws: &ws ^8.18.0
    "@types/ws": ^8.5.13
    qrcode-terminal: ^0.12.0
    "@types/qrcode-terminal": ^0.12.2
  utils:
    "@types/node": ^22.19.17
    c8: ^10.1.3
    chalk: 4.1.2
    commander: ^12.1.0
    rimraf: ^6.0.1
    tsx: ^4.19.0

useNodeVersion: 22.23.2
